# Do not set the language for c++, 
# this over rides our environment variable CXX below.
#language: c++

sudo: false
git:
    depth: 1

addons:
  apt:
    sources:
       - ubuntu-toolchain-r-test
    packages:
       - g++-5

os:
  - linux

env:
  - CXX=g++-5

# omr compiles with gcc, so ccache works for it
cache: ccache

install:
    - npm install

script:
    - make test
    - make bench
    - make program
